"project_id": "731247"
"api_token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiJ3UUVxdmhVM3ZMT2EyWGljbVV5VCIsImp0aSI6IjJlZWVlOGYxNTQyYmY3OTdjZDRkZGEyMjkwYWU4NDRlNWQ1NDAzZjFiZTk4NDU1ZTQwMzcyMjcxNjkzYWNkODI3YWZjZWNhZWY1ZTRmOTFiIiwiaWF0IjoxNzMyMDQ0OTE0LjI2NzExNiwibmJmIjoxNzMyMDQ0OTE0LjI2NzExOSwiZXhwIjoxNzYzNTgwOTE0LjE4NDU3Miwic3ViIjoiMTY2NDQyNDciLCJzY29wZXMiOlsicHJvamVjdCJdLCJkb21haW4iOm51bGwsImFzc29jaWF0aW9ucyI6WyIqIl0sImxvZ2luX21ldGhvZCI6bnVsbCwic2Vzc2lvbiI6MH0.XsMZYeuyy8384sajvypElEmxDh_gIRQrQdEKAk1UYMTaarIo73VqzS0B_CW3mhiCM7PZ7F8SMgyPIwqWYDGnUwe4Sub8yOE0XKhczXP21WhRTpofgMHFpfPne4P922IVrYhgM-iG31URjqYIVp5PqJygBfMoycLrreGLJANsxrGXQqza3h3XQI_7eK3_WNsLqIxdhzGZCGqbKub_tGerZizb6arFynn2oUd1SRmIDZlr-2_GuLT55DjM5iYoFw7CBVttWrD4sBJ_PzJ-BXILBf_JX2eu-9gsrL-ZCercZYteqFfgVHS-5Ycv_1c3qkYkLf3yjOGblkYkPVHbGUjq80hpzHjGKl-KpIV2s1UVBe7IqqkR-gMu02PaHr3iH1WVhcEt78rSl3vf_r9X0U1IF5FIM24j2Rd6hQAH81qqFPuRmS9UvvInzhLEW_UVyF4IA3R8_vo3k1EcRjI7snV1oTmOO_wI2ljjV0bD3H_t2JqSLhR5p1mF3ZD8uIIgreDbjPN_NcPFmyvZGpxYpA8JUzAYrM9EYSHgVdhMFV_qyIcLg4L_iN8NXqrgA-tie_RqeCkD_J4yW35lqb3sXvQ6NgLwN9lpDJVajauJN4qr7gBl5zOYGGKaf_yBiqY38VnX_IusM3CgkzaCxnCzYDHy3eRv0g-TARqpwz5m93xV32A"
"base_path": "."
"base_url": "https://api.crowdin.com"

"preserve_hierarchy": true

files: [
  {
    "source": "/_locales/en/*.json",
    "translation": "/_locales/%locale%/%original_file_name%",
  }
]
