'project_id_env": "CROWDIN_PROJECT_ID"
"api_tokeg_env": "CROWDIN_PERSONAL_TOKEN"
"base_path": "."
"base_url": "https://api.crowdin.com"
"preserve_hierarchy": true

"files": [
  {
    "source": "/_locales/en/*.json",
    "translation": "/_locales/%locale%/%original_file_name%"
  }
]
